[workspace]
members = [ "collect", "controlFlow", "enums", "exception", "functions",
  "guess_number", "matches", "ownership", "ownership_slice", "project", "structor", "util", "util_wasm", "variable",
]
