[package]
name = "util_wasm"
version = "0.1.0"
edition = "2024"

# 告诉 Cargo 我们要生成一个动态链接库（cdylib），这是 WebAssembly 所需要的格式
[lib]
crate-type=["cdylib"]

[dependencies]
wasm-bindgen = "0.2" #  Rust 与 JavaScript 之间进行交互的重要工具